apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 3311
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3311
      targetPort: 3311